name: Generate Snake

on:
  schedule:
    - cron: "30 8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Generate snakes
        uses: Platane/snk@master
        with:
          github_user_name: walidbosso
          # gif_out_path: src/img/snake.gif
          svg_out_path: src/img/snake.svg

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          author_name: "snk"
          message: ":octocat:"
